eStore/Controllers/BrandManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eStore.Models;
using PagedList;

namespace eStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BrandManagerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BrandManager
        public ActionResult Index(int? pageNo)
        {
            var brands = from b in db.Brands select b;
            brands = brands.OrderBy(b => b.BrandId);
            return View(brands.ToPagedList(pageNo ?? 1, 5));
        }

        // GET: BrandManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: BrandManager/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BrandManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BrandId,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                if (db.Brands.Any(b => b.BrandName == brand.BrandName))
                {
                    ViewBag.Create = "هذه الماركة موجودة.";
                    return View(brand);
                }
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: BrandManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: BrandManager/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BrandId,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: BrandManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: BrandManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eStore/Views/BrandManager/Create.cshtml
@model eStore.Models.Brand

@{
    ViewBag.Title = "إضافة ماركة جديدة";
}

<h2>@ViewBag.Title</h2>
<hr />
@if (ViewBag.Create != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Create
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrandName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="إضافة" class="btn btn-primary" /> |
                @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eStore/Views/BrandManager/Delete.cshtml
@model eStore.Models.Brand

@{
    ViewBag.Title = "حذف ماركة";
}

<h2>@ViewBag.Title</h2>
<hr />
<h3>هل أنت متأكد من حذف هذه الماركة؟</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandName)
        </dd>

    </dl>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color marg_butt">
            <input type="submit" value="حذف" class="btn btn-danger" /> |
            @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-dark" })
        </div>
    }
</div>

eStore/Views/BrandManager/Details.cshtml
@model eStore.Models.Brand

@{
    ViewBag.Title = "تفاصيل الماركة";
}

<h2>@ViewBag.Title</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandName)
        </dd>

    </dl>
</div>
<p class="marg_butt">
    @Html.ActionLink("تعديل", "Edit", new { id = Model.BrandId }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-dark" })
</p>

eStore/Views/BrandManager/Edit.cshtml
@model eStore.Models.Brand

@{
    ViewBag.Title = "تعديل ماركة";
}

<h2>@ViewBag.Title</h2>
<hr />
@using (Html.BeginForm("Edit", "BrandManager", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BrandId)
        <div class="form-group">
            @Html.LabelFor(model => model.BrandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrandName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="حفظ" class="btn btn-success" /> |
                @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eStore/Views/BrandManager/Index.cshtml
@model IEnumerable<eStore.Models.Brand>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "الماركات";
}
<h2>@ViewBag.Title</h2>
<hr />
<p>
    @Html.ActionLink("إضافة ماركة جديدة", "Create", null, htmlAttributes: new { @class = "btn btn-success" })
</p>
@if (Model.Count() == 0)
{
    <div class="alert alert-info" role="alert">
        لاتوجد بيانات
    </div>
}
else
{
    <table class="table table-bordered table-hover table-responsive d-sm-table text-center">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.SingleOrDefault().BrandName)
            </th>
            <th class="text-center">الأوامر</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandName)
                </td>
                <td>
                    @Html.ActionLink("تعديل", "Edit", new { id = item.BrandId }, new { @class = "btn btn-success" }) |
                    @Html.ActionLink("تفاصيل", "Details", new { id = item.BrandId }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("حذف", "Delete", new { id = item.BrandId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
}

@Html.PagedListPager((IPagedList)Model, PageNo => Url.Action(("Index"),
                 new { PageNo }), PagedListRenderOptions.OnlyShowFivePagesAtATime)

eStore/Views/BrandManager/QuantityOut.cshtml
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap-4.4.1.min.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        bootbox.alert("الكمية نفذت !",
            function() {
                var url = $("#RedirectTo").val();
                location.href = url;
            });
    });
</script>
@Html.Hidden("RedirectTo", Url.Action("Index", "Home"));