eStore/Controllers/UserAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using eStore.Models;
using eStore;

namespace eStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public ActionResult Index(string search, int? pageNo, string role)
        {
            var usersList = context.Users.Where(x => x.UserType != "Admin").Select(x => new UsersViewModel()
            {
                Id = x.Id,
                UserName = x.UserName,
                Email = x.Email,
                UserType = x.UserType,
                IsActive = x.IsActive
            });
            ViewBag.role = new SelectList(context.Roles.Where(x => x.Name != "Admin").ToList(), "Name", "Name");
            return View(usersList.OrderByDescending(x => x.Id).ToPagedList(pageNo ?? 1, 10));
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ViewBag.AccountType = new SelectList(await context.Roles.Where(x => x.Name != "Admin").ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userId = User.Identity.GetUserId();
                    var user = new ApplicationUser
                    {
                        UserName = userViewModel.Username,
                        Email = userViewModel.Email,
                        UserType = userViewModel.UserType,
                        IsActive = true,
                        EmailConfirmed = true,
                        Balance = 100000
                    };
                    var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                    //Add User to the selected Roles 
                    if (adminresult.Succeeded)
                    {
                        if (userViewModel.UserType != null)
                        {
                            var result = await UserManager.AddToRolesAsync(user.Id, userViewModel.UserType);
                            if (!result.Succeeded)
                            {
                                TempData["Message"] = "حدث خطأ غير متوقع عند إضافة الصلاحية لهذا المستخدم";
                                TempData["Status"] = 2;
                                ModelState.AddModelError("", result.Errors.First());
                                ViewBag.AccountType = new SelectList(await context.Roles.Where(x => x.Name != "Admin").ToListAsync(), "Name", "Name");
                                return View(userViewModel);
                            }
                        }
                    }
                    else
                    {
                        TempData["Message"] = "حدث خطأ غير متوقع";
                        TempData["Status"] = 2;
                        ModelState.AddModelError("", adminresult.Errors.First());
                        ViewBag.AccountType = new SelectList(await context.Roles.Where(x => x.Name != "Admin").ToListAsync(), "Name", "Name");
                        return View(userViewModel);
                    }
                    TempData["Message"] = "تمت إضافة المستخدم بنجاح";
                    TempData["Status"] = 1;
                    return RedirectToAction("Index");
                }
                catch 
                {
                    TempData["Message"] = "حدث خطأ غير متوقع";
                    TempData["Status"] = 2;
                }
            }
            ViewBag.AccountType = new SelectList(await context.Roles.Where(x => x.Name != "Admin").ToListAsync(), "Name", "Name");
            return View(userViewModel);
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRole = await UserManager.GetRolesAsync(user.Id);
            IEnumerable<SelectListItem> rolesList = context.Roles.Where(x => x.Name != "Admin")
                .ToList().Select(x => new SelectListItem()
                {
                    Selected = userRole.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                });
            ViewBag.UserType = rolesList;
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditUserViewModel editUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await UserManager.FindByIdAsync(editUser.Id);
                    if (user == null)
                    {
                        return HttpNotFound();
                    }

                    user.UserName = editUser.UserName;
                    user.Email = editUser.Email;
                    user.UserType = editUser.UserType;

                    var userRoles = await UserManager.GetRolesAsync(user.Id);

                    if (editUser.UserType != userRoles[0])
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, editUser.UserType);
                        if (!result.Succeeded)
                        {
                            TempData["Message"] = "حدث خطأ غير متوقع";
                            TempData["Status"] = 2;
                            ModelState.AddModelError("", result.Errors.First());
                            return View(editUser);
                        }
                    }
                    else
                    {
                        var userStore = new UserStore<ApplicationUser>(new ApplicationDbContext());
                        await UserManager.UpdateAsync(user);
                        var ctx = userStore.Context;
                        await ctx.SaveChangesAsync();
                    }

                    if (userRoles[0] != editUser.UserType)
                    {
                        await UserManager.RemoveFromRoleAsync(user.Id, userRoles[0]);
                    }
                    TempData["Message"] = "تم تعديل بيانات المستخدم بنجاح";
                    TempData["Status"] = 1;
                    return RedirectToAction("Index");
                }
                catch 
                {
                    TempData["Message"] = "حدث خطأ غير متوقع";
                    TempData["Status"] = 2;
                }
            }
            ModelState.AddModelError("", "حدث خطأ ما");
            var userRole = await UserManager.GetRolesAsync(editUser.Id);
            IEnumerable<SelectListItem> rolesList = context.Roles.Where(x => x.Name != "Admin")
                .ToList().Select(x => new SelectListItem()
                {
                    Selected = userRole.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                });
            ViewBag.UserType = rolesList;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> ChangeStatus(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            try
            {
                if (user.IsActive)
                {
                    user.IsActive = false;
                    TempData["Message"] = "تم إيقاف التفعيل بنجاح";
                }
                else
                {
                    user.IsActive = true;
                    TempData["Message"] = "تم التفعيل بنجاح";
                }
                TempData["Status"] = 1;
                await UserManager.UpdateAsync(user);
                await context.SaveChangesAsync();
            }
            catch 
            {
                TempData["Status"] = 2;
                TempData["Message"] = "حدث خطأ";
            }
            return RedirectToAction("Index");
        }

eStore/Views/UsersAdmin/Create.cshtml
@model eStore.Models.RegisterViewModel
@{
    ViewBag.Title = "إنشاء حساب جديد";
    var status = Convert.ToByte(TempData["Status"]);
}

@{
    if (status == 1)
    {
        <div class="alert alert-success">
            <span><strong>@TempData["Message"].ToString()</strong></span>
        </div>
    }
    else if (status == 2)
    {
        <div class="alert alert-danger">
            <span><strong>@TempData["Message"].ToString()</strong></span>
        </div>
    }
}
<h2>@ViewBag.Title</h2>
<hr />
@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Username, new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.DropDownListFor(m => m.UserType, (IEnumerable<SelectListItem>)ViewBag.AccountType, "اختيار الصلاحية", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success"> إضافة</button>
            <a href="@Url.Action("Index")" class="btn btn-secondary"> الرجوع إلى القائمة</a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eStore/Views/UsersAdmin/Delete.cshtml
@model eStore.Models.ApplicationUser

@{
    ViewBag.Title = "حذف مستخدم";
}

<h2>@ViewBag.Title</h2>
<hr />
<h3>هل تريد بالفعل حذف المستخدم - @Model.UserName ؟</h3>

<table class="table table-bordered table-hover table-responsive-sm text-center">
    <thead>
        <tr>
            <th class="text-center">
                اسم المستخدم
            </th>
            <th class="text-center">
                البريد الإلكتروني
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.UserType)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(model => model.UserName)
            </td>
            <td>
                @Html.DisplayFor(model => model.Email)
            </td>
            <td>
                @Html.DisplayFor(model => model.UserType)
            </td>
        </tr>
    </tbody>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="حذف" class="btn btn-danger" /> |
        @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-secondary" })
    </div>
}

eStore/Views/UsersAdmin/Edit.cshtml
@model eStore.Models.EditUserViewModel

@{
    ViewBag.Title = "تعديل بيانات مستخدم";
    var status = Convert.ToByte(TempData["Status"]);
}

@{
    if (status == 1)
    {
        <div class="alert alert-success">

            <span><strong>@TempData["Message"].ToString()</strong></span>
        </div>
    }
    else if (status == 2)
    {
        <div class="alert alert-danger">

            <span><strong>@TempData["Message"].ToString()</strong></span>
        </div>
    }
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Edit", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    @Html.DropDownListFor(m => m.UserType, (IEnumerable<SelectListItem>)ViewBag.AccountType, "اختيار الصلاحية", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary"> حفظ</button>
            <a href="@Url.Action("Index")" class="btn btn-secondary"> الرجوع إلى القائمة</a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#InDeptId").select2();
        $("#SelectedRole").select2();
    </script>
}

eStore/Views/UsersAdmin/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IEnumerable<eStore.Models.UsersViewModel>

@{
    ViewBag.Title = "المستخدمون";
    var c = 0;
    var status = Convert.ToByte(TempData["Status"]);
}

@{
    if (status == 1)
    {
        <div class="alert alert-success">
            <span><strong>@TempData["Message"].ToString()</strong></span>
        </div>
    }
    else if (status == 2)
    {
        <div class="alert alert-danger">
            <span><strong>@TempData["Message"].ToString()</strong></span>
        </div>
    }
}

<h2>@ViewBag.Title</h2>
<hr />
<p>
    <a href="@Url.Action("Create")" class="btn btn-success"><span class="glyphicon glyphicon-user"></span> إضافة مستخدم جديد</a>
</p>

<table class="table table-bordered table-hover table-responsive-sm text-center">
    <thead>
        <tr>
            <th class="text-center">#</th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.UserType)
            </th>
            <th class="text-center">
                الأوامر
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@{ c++; } @c</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.UserType)
                        </td>
                        <td>
                            <a href="@Url.Action("Edit",new { id = item.Id })" class="btn btn-warning"> تعديل </a>
                            <a href="@Url.Action("Delete",new { id = item.Id })" class="btn btn-danger"> حذف </a>
                            @{
                                if (item.IsActive)
                                {
                                    using (Html.BeginForm("ChangeStatus", "UsersAdmin", FormMethod.Post, new { @class = "form-inline" }))
                                    {
                                        @Html.Hidden("id", item.Id)
                                        <button type="submit" class="btn btn-secondary">إيقاف</button>
                                    }
                                }
                                else
                                {
                                    using (Html.BeginForm("ChangeStatus", "UsersAdmin", FormMethod.Post, new { @class = "form-inline" }))
                                    {
                                        @Html.Hidden("id", item.Id)
                                        <button type="submit" class="btn btn-success">تفعيل</button>
                                    }
                                }
                            }
                            @*<a href="@Url.Action("ResetPassword", "Account", new { Id = item.Id, Area = "" })" class="btn btn-info"> تهيئة كلمة المرور</a>*@
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">لاتوجد بيانات</td>
                </tr>
            }
        }
    </tbody>

</table>

<span class="text-center">
    @Html.PagedListPager((IPagedList)Model, pageNo => Url.Action("Index", "UsersAdmin",
                    new { pageNo }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
</span>