eStore/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eStore.Models
{
    public partial class ShoppingCart
    {
        ApplicationDbContext db = new ApplicationDbContext();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        public void AddToCart(Product product)
        {
            // Get the matching cart and product instances
            var cartItem = db.Carts.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                     && c.ProductId == product.ProductId);
            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    ProductId = product.ProductId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                db.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, then add one to the quantity
                cartItem.Count++;
            }
            // Save changes
            db.SaveChanges();
        }
        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = db.Carts.Single(
                cart => cart.CartId == ShoppingCartId
                        && cart.RecordId == id);
            int itemCount = 0;
            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    db.Carts.Remove(cartItem);
                }

                var a = db.Carts.Single(b => b.RecordId == id).ProductId;
                var product = db.Products.Find(a);
                product.TempQuantity += 1;
                db.Entry(product).State = EntityState.Modified;
                //db.SaveChanges();

                // Save changes
                db.SaveChanges();
            }
            return itemCount;
        }
        public void EmptyCart()
        {
            var cartItems = db.Carts.Where(cart => cart.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                db.Carts.Remove(cartItem);
            }
            // Save changes
            db.SaveChanges();
        }
        public List<Cart> GetCartItems()
        {
            return db.Carts.Where(cart => cart.CartId == ShoppingCartId).ToList();
        }
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in db.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }
        public decimal GetTotal()
        {
            // Multiply product price by count of that album to get
            // the current price for each of those products in the cart
            // sum all product price totals to get the cart total
            decimal? total = (from cartItems in db.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count * cartItems.Product.Price).Sum();
            return total ?? decimal.Zero;
        }
        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;
            var cartItems = GetCartItems();
            // Iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProductId = item.ProductId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count
                };
                // Set the order total of the shopping cart
                orderTotal += item.Count * item.Product.Price;
                db.OrderDetails.Add(orderDetail);


                //////////////////////////////////////////////
                item.Product.Quantity = item.Product.Quantity - item.Count;
                item.Product.TempQuantity = item.Product.Quantity;
                db.Entry(item).State = EntityState.Modified;
                ///////////////////////////////////////////////
            }
            // Set the order's total to the orderTotal count
            order.Total = orderTotal;
            // Save the order
            db.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return order.OrderId;
        }

        public decimal GetOrderTotal(Order order)
        {
            decimal orderTotal = 0;
            var cartItems = GetCartItems();
            // Iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProductId = item.ProductId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count
                };
                // Set the order total of the shopping cart
                orderTotal += item.Count * item.Product.Price;
            }
            return orderTotal;
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] = context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = db.Carts.Where(c => c.CartId == ShoppingCartId);
            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            }
            db.SaveChanges();
        }
    }
}

eStore/Models/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using eStore.Models;
using eStore.ViewModels;

namespace eStore.ViewModels
{
    public class ShoppingCartViewModel
    {
        public int Id { get; set; }
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

eStore/Controllers/CheckoutController.cs
using eStore.Models;
using System;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web.Mvc;

namespace eStore.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            return View();
        }
        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);
            try
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);
                order.Username = User.Identity.Name;
                order.OrderDate = DateTime.Now;
                order.Total = cart.GetOrderTotal(order);
                //Save Order
                db.Orders.Add(order);
                db.SaveChanges();
                //Process the order
                cart.CreateOrder(order);
                return RedirectToAction("Complete", new { id = order.OrderId });
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = db.Orders.Any(
                o => o.OrderId == id &&
                     o.Username == User.Identity.Name);
            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

eStore/Controllers/ShoppingCartController.cs
using eStore.Models;
using eStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eStore.Controllers
{
    [AllowAnonymous]
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the Product from the database
            var addedProduct = db.Products
                .Single(p => p.ProductId == id);


            if (addedProduct.Quantity > 0 && addedProduct.TempQuantity > 0 && (addedProduct.TempQuantity <= addedProduct.Quantity))
            {
                // Add it to the shopping cart
                var cart = ShoppingCart.GetCart(this.HttpContext);
                cart.AddToCart(addedProduct);
                //////////////////////////////////
                addedProduct.TempQuantity -= 1;
                db.Entry(addedProduct).State = EntityState.Modified;
                db.SaveChanges();
                //////////////////////////////////
            }
            else
            {
                return RedirectToAction("QuantityOut");
            }

            // Go back to the main store page for more shopping
            return RedirectToAction("Index", "Home");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Get the name of the product to display confirmation
            string productName = db.Carts
                .Single(item => item.RecordId == id).Product.ProductName;
            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);
            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = "تم حذف المنتج " + Server.HtmlEncode(productName) +
                          " من سلة التسوق.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            // increase quantity
            return Json(results);
        }
        [ChildActionOnly]
        public ActionResult QuantityOut()
        {
            return View();
        }

        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

eStore/Controllers/StoreController.cs
using eStore.Models;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;

namespace eStore.Controllers
{
    [AllowAnonymous]
    public class StoreController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(int? brandId, int? genreId, string search, int? pageNo)
        {
            var products = from p in db.Products.Include(b => b.Attachments) select p;
            if (brandId != null)
            {
                products = products.Where(b => b.BrandId == brandId);
                ViewBag.BrandId = brandId;
                ViewBag.Name = db.Brands.SingleOrDefault(x => x.BrandId == brandId).BrandName;
            }
            if (genreId != null)
            {
                products = products.Where(g => g.GenreId == genreId);
                ViewBag.GenreId = genreId;
                ViewBag.Name = db.Genres.SingleOrDefault(x => x.GenreId == genreId).GenreName;
            }
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.ProductName.Contains(search) ||
                                          p.Brand.BrandName.Contains(search) ||
                                          p.Genre.GenreName.Contains(search));
            }
            products = products.OrderByDescending(p => p.ProductId);
            return View(products.ToPagedList(pageNo ?? 1, 6));
        }
        public ActionResult ProductDetails(int? id)
        {
            var product = db.Products.Include(x => x.Attachments).Include(x => x.Brand).Include(x => x.Attachments).FirstOrDefault(x => x.ProductId == id);
            return View(product);
        }
        [ChildActionOnly]
        public ActionResult BrandsMenu()
        {
            return PartialView(db.Brands.ToList());
        }
        [ChildActionOnly]
        public ActionResult GenresMenu()
        {
            return PartialView(db.Genres.ToList());
        }
    }
}

eStore/Views/ShoppingCart/CartSummary.cshtml
<li class="nav-item">
    <a class="nav-link btn" href="@Url.Action("Index","ShoppingCart")" id="cart-status">
        سلّة التسوق
        <span class="badge bg-info rounded-pill">@ViewData["CartCount"]</span>
    </a>
</li>

eStore/Views/ShoppingCart/Index.cshtml
@using System.Diagnostics.Eventing.Reader
@model eStore.ViewModels.ShoppingCartViewModel

@{
    ViewBag.Title = "سلّة التسوق";
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script type="text/javascript">
    $(function () {
        //$("#cart-table").dataTable();

        $(".RemoveLink").click(
            function () {
                var recordToDelete = $(this).attr("data-id");
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.ItemCount == 0) {
                                $('#row-' + data.DeleteId).fadeOut('slow');
                            }
                            else {
                                $('#item-count-' + data.DeleteId).text(data.ItemCount);
                            }
                            $('#update-message').show();
                            $('#cart-total').text(data.CartTotal);
                            $('#update-message').text(data.Message).fadeOut(5000);
                            $('#cart-status').text(data.CartCount);
                        });
                }
            });
    });
    function handleUpdate() {
        // Load and deserialize the returned JSON data
        var json = context.get_data();
        var data = Sys.Serialization.JavaScriptSerializer.deserialize(json);
        // Update the page elements
        if (data.ItemCount == 0) {
            $('#row-' + data.DeleteId).fadeOut('slow');
        } else {
            $('#item-count-' + data.DeleteId).text(data.ItemCount);
        }
        $('#cart-total').text(data.CartTotal);
        $('#update-message').text(data.Message);
        $('#cart-status').text('Cart (' + data.CartCount + ')');
    }
</script>
<h3>
    راجع سلّة التسوق خاصتك
</h3>
<hr />
@Html.ActionLink("إتمام الشراء", "AddressAndPayment", "Checkout", null, new { @class = "btn btn-primary" })
<table id="cart-table" class="table table-bordered table-hover table-responsive d-sm-table text-center">
    <thead>
        <tr>
            <th class="text-center">
                اسم المنتج
            </th>
            <th class="text-center">
                السعر (قطعة)
            </th>
            <th class="text-center">
                الكمية
            </th>
            <th class="text-center">الأوامر</th>
        </tr>
    </thead>
    <tbody>
        @{

            if (Model.CartTotal == 0)
            {
                <tr class="alert alert-info" role="alert"><td>لاتوجد منتجات في سلة التسوق الخاصة بك!</td><td></td><td></td><td></td></tr>
            }
            else
            {
                foreach (var item in Model.CartItems)
                {
                    <tr id="row-@item.RecordId">
                        <td>
                            @Html.ActionLink(item.Product.ProductName, "ProductDetails", "Store", new { id = item.ProductId }, null)
                        </td>
                        <td>
                            @item.Product.Price
                        </td>
                        <td id="item-count-@item.RecordId">
                            @item.Count
                        </td>
                        <td>
                            <a href="#" class="RemoveLink btn btn-danger" data-id="@item.RecordId">حذف من السلّة</a>
                        </td>
                    </tr>
                }
                <tr>
                    <td>
                        الإجمالي
                    </td>
                    <td></td>
                    <td></td>
                    <td id="cart-total">
                        @Model.CartTotal
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div id="update-message" class="alert alert-danger" role="alert" style="display: none">
</div>
<p>
    @Html.ActionLink("الصفحة الرئيسية", "Index", "Home", null, new { @class = "btn btn-dark" })
</p>