eStore/Controllers/GenreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eStore.Models;
using PagedList;

namespace eStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GenreManagerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: GenreManager
        public ActionResult Index(string search, int? pageNo)
        {
            var genres = from g in db.Genres select g;
            if (!String.IsNullOrEmpty(search))
            {
                genres = genres.Where(g => g.GenreName.Contains(search));
            }
            genres = genres.OrderBy(g => g.GenreId);
            return View(genres.ToPagedList(pageNo ?? 1, 5));
        }

        // GET: GenreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // GET: GenreManager/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GenreManager/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GenreId,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                if (db.Genres.Any(g => g.GenreName == genre.GenreName))
                {
                    ViewBag.Create = "هذا الصنف موجود.";
                    return View(genre);
                }
                db.Genres.Add(genre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        // GET: GenreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: GenreManager/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GenreId,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        // GET: GenreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: GenreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Genre genre = db.Genres.Find(id);
            db.Genres.Remove(genre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eStore/Views/GenreManager/Create.cshtml
@model eStore.Models.Genre

@{
    ViewBag.Title = "إضافة صنف جديد";
}

<h2>@ViewBag.Title</h2>
<hr />
@if (ViewBag.Create != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Create
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="إضافة" class="btn btn-primary" /> |
                @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eStore/Views/GenreManager/Delete.cshtml
@model eStore.Models.Genre

@{
    ViewBag.Title = "حذف صنف";
}

<h2>@ViewBag.Title</h2>
<hr />
<h3>هل أنت متأكد من حذف هذا الصنف؟</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color marg_butt">
            <input type="submit" value="حذف" class="btn btn-danger" /> |
            @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-dark" })
        </div>
    }
</div>

eStore/Views/GenreManager/Details.cshtml
@model eStore.Models.Genre

@{
    ViewBag.Title = "تفاصيل الصنف";
}

<h2>@ViewBag.Title</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>

    </dl>
</div>
<p class="marg_butt">
    @Html.ActionLink("تعديل", "Edit", new { id = Model.GenreId }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-dark" })
</p>

eStore/Views/GenreManager/Edit.cshtml
@model eStore.Models.Genre

@{
    ViewBag.Title = "تعديل صنف";
}

<h2>@ViewBag.Title</h2>
<hr />
@using (Html.BeginForm("Edit", "GenreManager", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GenreId)
        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="حفظ" class="btn btn-success" /> |
                @Html.ActionLink("العودة إلى القائمة", "Index", null, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eStore/Views/GenreManager/Index.cshtml
@model IEnumerable<eStore.Models.Genre>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "الأصناف";
}
<h2>@ViewBag.Title</h2>
<hr />
<p>
    @Html.ActionLink("إضافة صنف جديد", "Create", null, htmlAttributes: new { @class = "btn btn-success" })
</p>
@if (Model.Count() == 0)
{
    <div class="alert alert-info" role="alert">
        لاتوجد بيانات
    </div>
}
else
{
    <table class="table table-bordered table-hover table-responsive d-sm-table text-center">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.SingleOrDefault().GenreName)
            </th>
            <th class="text-center">الأوامر</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GenreName)
                </td>
                <td>
                    @Html.ActionLink("تعديل", "Edit", new { id = item.GenreId }, new { @class = "btn btn-success" }) |
                    @Html.ActionLink("تفاصيل", "Details", new { id = item.GenreId }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("حذف", "Delete", new { id = item.GenreId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
}

@Html.PagedListPager((IPagedList)Model, PageNo => Url.Action(("Index"),
                 new { PageNo }), PagedListRenderOptions.OnlyShowFivePagesAtATime)